nelmio_api_doc:
    documentation:
        info:
            title: Sloan 2018 REST API
            description: Endpoints used with the Sloan REST APIs and JSON Graphs Workshop
            version: 1.0.0
    routes: # to filter documented routes
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
            - ^/public/api/ # Accepts routes under /public/api
